dist: trusty
sudo: required

git:
  depth: 3

language: rust
rust:
  - stable
#  - beta

#matrix:
#  allow_failures:
#    - rust:
#        - beta
#  fast_finish: true

#cache:
# - cargo

notifications:
  email: false

install:
 - cargo install --force cargo-check
# - sudo apt-get upgrade
 - sudo apt-get install llvm-3.6-dev -y
 - sudo apt-get install llvm-3.6-dev -y

script:
  - llvm-config --version
  - cargo check --verbose
  - cargo test --verbose
