sudo: false

git:
  depth: 3

language: rust
rust:
  - stable
  - beta

addons:
  apt:
    packages:
      - llvm-2.9-dev
      - llvm-2.9-runtime

matrix:
  allow_failures:
    - rust:
        - beta
  fast_finish: true

cache:
 - cargo

notifications:
  email: false

#install:
# - cargo install --force cargo-check

script:
  - llvm-config --version
  - cargo check --verbose
  - cargo test --verbose
