language: rust
git:
  depth: 3
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust:
        - nightly
        - beta
  fast_finish: true
notifications:
  email: false
script:
  - cargo test --verbose
