# Protosnirk CI setup:
#   - add LLVM package credentials
#   - install LLVM from their apt package
#   - `cargo check`
#   - `cargo test`

# I would like to thank Zig for having a working
# Travis setup with LLVM. I'm following their .travis.yml
# and other CI scripts.

# Zig is an MIT-licensed open-source programming language,
# available at https://github.com/zig-lang/zig

dist: trusty
sudo: required

git:
  depth: 3

language: rust
rust:
  - stable
  - beta

matrix:
  allow_failures:
    - rust:
        - beta
  fast_finish: true

cache:
  - cargo

notifications:
  email: false

before_install:
  - sudo sh -c 'echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main" >> /etc/apt/sources.list'
  - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -q

install:
  - sudo apt-get remove -y llvm-*
  - sudo rm -rf /usr/local/*
  - sudo apt-get install -y clang-5.0 libclang-5.0 libclang-5.0-dev llvm-5.0 llvm-5.0-dev liblld-5.0 liblld-5.0-dev

script:
  - cargo check --verbose
  - cargo test --verbose
