[package]
name = "protosnirk"
description = "An in-progress simple programming language implemented in Rust"
version = "0.0.1"
repository = ""
keywords = ["protosnirk", "programming", "scripting", "language"]
readme = "README.md"
authors = ["Snirk Immington <snirk.immington@gmail.com>"]
license = "MIT"

[dependencies]
maplit = "*"
unicode_categories = "0.1"
llvm-sys = "40.0.2"
log = "*"
env_logger = "*"

[dev-dependencies]
lazy_static = "0.2"

[dependencies.iron_llvm]
git = "https://github.com/Immington-Industries/iron-llvm"
branch = "llvm-4.0"
